image: node

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - npm install --force

      - step:
          name: Build
          script:
            - npm install --force && npm run build
          artifacts:
            - dist/**

      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:0.2.1
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: $FIREBASE_PROJECT
